# Generated by Django 5.2.5 on 2026-02-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0002_portfolio_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='services',
            field=models.TextField(blank=True),
        ),
    ]
