# Generated by Django 5.2.5 on 2026-02-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0004_portfolios_project_delete_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
