# Generated by Django 5.2.5 on 2026-02-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0005_portfolios_about_portfolios_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolios',
            name='projects',
        ),
    ]
